using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Persistence.Configurations
{
    internal class ReviewConfigurations : IEntityTypeConfiguration<Domain.Entities.Review>
    {
        public void Configure(EntityTypeBuilder<Review> builder)
        {
            // Primary Key
            builder.HasKey(r => r.Id);
            // Generated by the database
            builder.Property(r => r.Id)
                   .ValueGeneratedOnAdd();

            #region Properties Constrains
            // Date Generated by the database
            builder.Property(r => r.Date)
                   .HasDefaultValueSql("GETDATE()");

            // Set the maximum value for Rate to 5
            builder.Property(r => r.Rate)
                   .HasDefaultValue(0)
                   .IsRequired()
                   .HasConversion(
                     v => Convert.ToInt32(v),
                     v => Convert.ToInt32(v))
                   .HasMaxLength(5)
                   .HasColumnType("int");
            // Set the maximum length for Comment to 100 characters
            builder.Property(r => r.Comment)
                   .HasMaxLength(100);
            #endregion
        }
    }
}
